const root=document.documentElement;const opening=document.querySelector('[data-opening]');const journey=document.querySelector('[data-journey]');const room=document.querySelector('[data-room]');const roomImg=room?.querySelector('img');const threshold=document.querySelector('[data-threshold]');const thresholdImg=threshold?.querySelector('img');const titleBox=document.querySelector('[data-scene-title]');const titleSmall=titleBox?.querySelector('small');const titleH2=titleBox?.querySelector('h2');const metaSmall=document.querySelector('[data-meta-small]');const metaStrong=document.querySelector('[data-meta-strong]');const metaQuote=document.querySelector('[data-meta-quote]');const loader=document.querySelector('[data-loader]');const filmObject=document.querySelector('[data-film-object]');const filmVideo=filmObject?.querySelector('video');const btsObject=document.querySelector('[data-bts-object]');const magObject=document.querySelector('[data-mag-object]');const magCaption=document.querySelector('[data-mag-caption]');const eclipse=document.querySelector('[data-eclipse]');const map=document.querySelector('[data-map]');const gate=document.querySelector('[data-gate]');
const scenes=[
{src:'https://res.cloudinary.com/vysyrabp/image/upload/v1787319165/first-glimpse.webp',title:'The First Glimpse',meta:'CAM 01 · Arrival',quote:'The house appears before the day fully does.',shape:'arch',x:50,y:49,w:20,h:48},
{src:'https://res.cloudinary.com/vysyrabp/image/upload/v1787319213/the-arrival.webp',title:'The Arrival',meta:'CAM 20 · Threshold',quote:'Every story needs a threshold.',shape:'arch',x:54,y:50,w:18,h:52},
{src:'https://res.cloudinary.com/vysyrabp/image/upload/v1787319221/bougainvillea-courtyard.webp',title:'The Bougainvillea Courtyard',meta:'CAM 18 · Garden',quote:'The garden begins speaking in color.',shape:'circle',x:65,y:42,w:16,h:30},
{src:'https://res.cloudinary.com/vysyrabp/image/upload/v1787319237/the-passage.webp',title:'The Passage',meta:'CAM 07 · Interior',quote:'Inside, light becomes architecture.',shape:'arch',x:45,y:48,w:17,h:51},
{src:'https://res.cloudinary.com/vysyrabp/image/upload/v1787319229/morning-beyond.webp',title:'The Morning Beyond',meta:'CAM 06 · Morning',quote:'The rooms keep borrowing the garden.',shape:'slit',x:70,y:47,w:11,h:54},
{src:'https://res.cloudinary.com/vysyrabp/image/upload/v1787319249/sun-was-waiting.webp',title:'The Sun Was Waiting',meta:'CAM 03 · Afternoon',quote:'At noon, every surface becomes a clock.',shape:'arch',x:50,y:49,w:20,h:46},
{src:'https://res.cloudinary.com/vysyrabp/image/upload/v1787319325/fountain-keeps-time.webp',title:'The Fountain Keeps Time',meta:'DETAIL 06 · Texture',quote:'Some hours are measured in water.',shape:'water',x:42,y:68,w:25,h:16},
{src:'https://res.cloudinary.com/vysyrabp/image/upload/v1787319300/golden-company.webp',title:'Golden Company',meta:'DETAIL 20 · Ritual',quote:'The house is most alive in small rituals.',shape:'mirror',x:66,y:48,w:18,h:42},
{src:'https://res.cloudinary.com/vysyrabp/image/upload/v1787319334/between-the-pages.webp',title:'Between the Pages',meta:'DETAIL 07 · Still life',quote:'A room can ask you to stay a little longer.',shape:'mirror',x:38,y:49,w:20,h:42},
{src:'https://res.cloudinary.com/vysyrabp/image/upload/v1787319258/petals-afloat.webp',title:'Petals Afloat',meta:'CAM 17 · Water',quote:'Then the afternoon begins to loosen.',shape:'water',x:50,y:67,w:28,h:17},
{src:'https://res.cloudinary.com/vysyrabp/image/upload/v1787319308/petals-on-water.webp',title:'Petals on Water',meta:'DETAIL 22 · Detail',quote:'Light touches the water one last time.',shape:'circle',x:34,y:56,w:18,h:30},
{src:'https://res.cloudinary.com/vysyrabp/image/upload/v1787319293/view-she-carries.webp',title:'The View She Carries',meta:'CAM 16 · Life at Casa',quote:'And suddenly the house belongs to evening.',shape:'slit',x:68,y:48,w:12,h:54},
{src:'https://res.cloudinary.com/vysyrabp/image/upload/v1787319270/after-lights.webp',title:'After the Lights Come On',meta:'CAM 23 · Night',quote:'When daylight leaves, Casa answers with its own.',shape:'arch',x:52,y:51,w:18,h:50},
{src:'https://res.cloudinary.com/vysyrabp/image/upload/v1787319277/moonlit-threshold.webp',title:'Moonlit Threshold',meta:'CAM 13 · Nocturne',quote:'The thresholds become lanterns.',shape:'arch',x:46,y:49,w:17,h:50},
{src:'https://res.cloudinary.com/vysyrabp/image/upload/v1787319284/eclipse-witness.webp',title:'Eclipse Witness',meta:'CAM 29 · 12:11',quote:'For one impossible moment, the sun went quiet.',shape:'circle',x:50,y:38,w:12,h:20}
];
const clamp=(v,a=0,b=1)=>Math.min(Math.max(v,a),b);const smooth=t=>t*t*(3-2*t);const lerp=(a,b,t)=>a+(b-a)*t;
let mx=0,my=0,tmx=0,tmy=0;window.addEventListener('pointermove',e=>{tmx=(e.clientX/window.innerWidth-.5)*2;tmy=(e.clientY/window.innerHeight-.5)*2},{passive:true});
function setSceneCopy(scene,opacity){if(!scene)return;titleSmall.textContent=scene.meta;titleH2.textContent=scene.title;titleBox.style.setProperty('--title-o',opacity.toFixed(3));metaSmall.textContent=scene.meta;metaStrong.textContent=scene.title;metaQuote.textContent=scene.quote}
function setThreshold(scene,p){threshold.className=`threshold-room ${scene.shape}`;threshold.style.setProperty('--tx',`${scene.x}%`);threshold.style.setProperty('--ty',`${scene.y}%`);const s=smooth(clamp((p-.08)/.82));const targetScale=7.4;threshold.style.setProperty('--ts',(1+s*(targetScale-1)).toFixed(3));threshold.style.setProperty('--tw',`${scene.w}vw`);threshold.style.setProperty('--th',`${scene.h}vh`);threshold.style.setProperty('--threshold-img-scale',(1.08-s*.06).toFixed(3));root.style.setProperty('--glow',(Math.sin(s*Math.PI)*.48).toFixed(3))}
function pulse(local,start,end,fade=.12){const a=clamp((local-start)/fade);const b=clamp((end-local)/fade);return smooth(Math.min(a,b))}
function specialRooms(index,local){const film=index===5?pulse(local,.17,.78,.14):0;root.style.setProperty('--film-o',film.toFixed(3));root.style.setProperty('--film-scale',(0.68+film*.32).toFixed(3));filmObject?.classList.toggle('is-active',film>.2);if(film>.25)filmVideo?.play().catch(()=>{});else filmVideo?.pause();const bts=index===9?pulse(local,.18,.82,.14):0;root.style.setProperty('--bts-o',bts.toFixed(3));btsObject?.classList.toggle('is-active',bts>.2);const mag=index===7?pulse(local,.2,.8,.14):0;root.style.setProperty('--mag-o',mag.toFixed(3));magObject?.classList.toggle('is-active',mag>.2);if(magCaption)magCaption.style.opacity=mag.toFixed(3);const ecl=index>=13?smooth(clamp((index===13?local*.35:(index===14?.35+local*.65:0)))):0;const ring=index===14?smooth(clamp((local-.18)/.42)):0;root.style.setProperty('--eclipse-dark',(ecl*.78).toFixed(3));root.style.setProperty('--ring',ring.toFixed(3))}
let lastRoom=-1,lastNext=-1,ticking=false;
function update(){mx=lerp(mx,tmx,.055);my=lerp(my,tmy,.055);root.style.setProperty('--mx',mx.toFixed(3));root.style.setProperty('--my',my.toFixed(3));if(opening){const r=opening.getBoundingClientRect();const total=Math.max(opening.offsetHeight-innerHeight,1);const op=clamp(-r.top/total);root.style.setProperty('--opening-p',op.toFixed(4))}if(journey){const r=journey.getBoundingClientRect();const total=Math.max(journey.offsetHeight-innerHeight,1);const p=clamp(-r.top/total);root.style.setProperty('--p',p.toFixed(4));const scaled=p*(scenes.length-1);const idx=Math.min(Math.floor(scaled),scenes.length-2);const local=clamp(scaled-idx);root.style.setProperty('--local',local.toFixed(4));const cur=scenes[idx],next=scenes[idx+1];if(lastRoom!==idx){roomImg.src=cur.src;roomImg.alt=`Casa Sol Tardío — ${cur.title}`;lastRoom=idx}if(lastNext!==idx+1){thresholdImg.src=next.src;thresholdImg.alt=`Casa Sol Tardío — ${next.title}`;lastNext=idx+1}root.style.setProperty('--room-zoom',local.toFixed(3));root.style.setProperty('--room-bright',(1-local*.18).toFixed(3));root.style.setProperty('--next-bright',(0.9+local*.1).toFixed(3));setThreshold(next,local);const titleOpacity=pulse(local,.03,.5,.14);setSceneCopy(local<.48?cur:next,titleOpacity);specialRooms(idx,local);if(idx===scenes.length-2&&local>.93){roomImg.src=scenes.at(-1).src;roomImg.alt=`Casa Sol Tardío — ${scenes.at(-1).title}`;setSceneCopy(scenes.at(-1),1)}}ticking=false}
function requestUpdate(){if(ticking)return;ticking=true;requestAnimationFrame(update)}window.addEventListener('scroll',requestUpdate,{passive:true});window.addEventListener('resize',requestUpdate,{passive:true});(function loop(){requestUpdate();requestAnimationFrame(loop)})();
window.addEventListener('load',()=>setTimeout(()=>loader?.classList.add('is-gone'),300),{once:true});setTimeout(()=>loader?.classList.add('is-gone'),2400);
const openingVideo=document.querySelector('.opening-video');openingVideo?.play().catch(()=>{});
const mapTrigger=document.querySelector('[data-map-trigger]');const mapClose=document.querySelector('[data-map-close]');mapTrigger?.addEventListener('click',()=>{map?.classList.add('is-open');document.body.classList.add('is-locked')});mapClose?.addEventListener('click',()=>{map?.classList.remove('is-open');document.body.classList.remove('is-locked')});
document.querySelectorAll('[data-jump]').forEach(btn=>btn.addEventListener('click',()=>{const ratio=Number(btn.dataset.jump);map?.classList.remove('is-open');document.body.classList.remove('is-locked');const top=journey.offsetTop+ratio*Math.max(journey.offsetHeight-innerHeight,1);window.scrollTo({top,behavior:'smooth'})}));
const lightbox=document.querySelector('[data-lightbox]');const lbImg=lightbox?.querySelector('img');function openLightbox(src,alt){if(!lightbox||!lbImg)return;lbImg.src=src;lbImg.alt=alt||'';lightbox.classList.add('is-open');document.body.classList.add('is-locked')}document.querySelector('[data-room-open]')?.addEventListener('click',()=>openLightbox(roomImg.src,roomImg.alt));document.querySelector('[data-threshold-open]')?.addEventListener('click',()=>openLightbox(thresholdImg.src,thresholdImg.alt));document.querySelector('[data-lb-close]')?.addEventListener('click',()=>{lightbox.classList.remove('is-open');document.body.classList.remove('is-locked')});
const openGate=document.querySelectorAll('[data-open-gate]');const closeGate=document.querySelector('[data-close-gate]');openGate.forEach(btn=>btn.addEventListener('click',()=>gate?.showModal?.()));closeGate?.addEventListener('click',()=>gate?.close());gate?.addEventListener('click',e=>{const r=gate.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)gate.close()});document.querySelector('[data-gate-form]')?.addEventListener('submit',e=>{e.preventDefault();const note=e.currentTarget.querySelector('.gate-note');if(note)note.textContent='The private Casa presentation will open through this door.'});
document.addEventListener('keydown',e=>{if(e.key==='Escape'){if(lightbox?.classList.contains('is-open')){lightbox.classList.remove('is-open');document.body.classList.remove('is-locked')}else if(map?.classList.contains('is-open')){map.classList.remove('is-open');document.body.classList.remove('is-locked')}}});